import { printBlockComment } from '@clientql/codegen'
import { indent, TypescriptString } from '@clientql/core'
import { ASTNode, print } from 'graphql'

/**
 *  prints graphql to gql tagged constant
 */
export const printTsGql = (
  constant: TypescriptString,
  content: ASTNode,
  deps?: TypescriptString[],
) => {
  let result = ''

  result += `export const ${constant} = gql\`\n`
  result += indent(print(content), 1)

  if (deps) {
    result += '\n\n'
    result += indent(deps.map(dep => '${' + dep + '}').join('\n'), 1)
  }

  result += `\n\``

  return result
}

// Code generated by Graphql Client Generator.
// DO NOT EDIT.
// Please don't change this file manually but run 'something' to update it.
// For more information, please read the docs: https://doclink.com/

const YADA_YADA = `
Code generated by Graphql Client Generator.
DO NOT EDIT.
Please don't change this file manually but run 'something' to update it.
For more information, please read the docs: https://doclink.com/
`.trim()

export const printYadaYada = () => printBlockComment(YADA_YADA)
